version: '3.3'

services:
  # frontend:
    # backend:
    #     container_name: node_app
    #     build: ./backend
    #     ports:
    #       - "8888:8888"
    #     links:
    #       - mongodb
    #     environment:
    #       MONGODB_URI: mongodb://mongodb:27017/frontcamp
    #       NODE_ENV: production
    #       PORT: 8888
    #       # SECURITY_MODE: "true"
    #       DEBUG: "false"
    #     depends_on: 
    #       - mongodb
    mongodb:
      container_name: mongo_instance
      image: mongo:latest
      ports:
        - "27017:27017"
    # Will be comment after import
    mongo_seed:
      container_name: mongo_seed
      build: ./mongo
      links:
        - mongodb