// User commands
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS_USER = 'REGISTER_SUCCESS_USER';
export const REGISTER_ERROR_USER = 'REGISTER_ERROR_USER';

// Blog commands
export const LOAD_ALL_BLOGS = 'LOAD_ALL_BLOGS';
export const BEGIN_LOADING_ALL_BLOGS = 'BEGIN_LOADING_BLOGS';
export const ERROR_LOADING_ALL_BLOGS = 'ERROR_LOADING_BLOGS';
export const SUCCESS_LOADING_ALL_BLOGS = 'SUCCESS_LOADING_BLOGS';

export const CREATE_BLOG = 'LOAD_ALL_BLOGS';
export const BEGIN_CREATE_BLOG = 'BEGIN_CREATE_BLOG';
export const ERROR_CREATE_BLOG = 'ERROR_CREATE_BLOG';
export const SUCCESS_CREATE_BLOG = 'SUCCESS_CREATE_BLOG';

export const DELETE_BLOG = 'LOAD_DELETE_BLOG';
export const BEGIN_DELETE_BLOG = 'BEGIN_DELETE_BLOG';
export const ERROR_DELETE_BLOG = 'ERROR_DELETE_BLOG';
export const SUCCESS_DELETE_BLOG = 'SUCCESS_DELETE_BLOG';
